
server:
  port: 8082

spring:
  application:
    name: energy-consumer-app
  #profiles: dev
eureka:
  client:
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-01-fnw-release.topaas.enncloud.cn/eureka,http://eureka-02-fnw-release.topaas.enncloud.cn/eureka,http://eureka-03-fnw-release.topaas.enncloud.cn/eureka
  instance:
      lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true     # 访问的路径变为IP地址
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000

index:
  mobile: 400-789-8555

swagger:
  show: true

security:
  user:
    name: admin
    password: admin
  basic:
    path: /v2/api-docs

