#生产环境
spring:
  application:
    name: energy-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-01-fnw-release.topaas.enncloud.cn/eureka,http://eureka-02-fnw-release.topaas.enncloud.cn/eureka,http://eureka-03-fnw-release.topaas.enncloud.cn/eureka

  instance:
      lease-renewal-interval-in-seconds: 5 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 10 # 如果现在超过了5秒的间隔（默认是90秒）
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: false     # 访问的路径变为IP地址
      hostname: energy-zuul-gateway-fnw-release.topaas.enncloud.cn
      non-secure-port: 80



zuul:
  AuthorizedRequestFilter:
    pre:
      disable: false
  prefix: /energy-proxy
  ignored-services:
    "*"
  routes:
    energy-provider-business: /energy-provider-business/**
    energy-provider-system: /energy-provider-system/**
    energy-provider-passage: /energy-provider-passage/**




ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000